import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar/Navbar";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className={styles.header_section}>
        <div className={styles.header_image}>
          <div className={styles.header_content}>
            <div className={styles.header_text}>
              <div className={styles.header_headline_wrap}>
                <p className="label">BEST PLACE TO BUY DESIGN</p>
                <div className={styles.header_headline}>Coffe Mugs</div>
                <p className="big-paragraph">
                  The most versatile furniture system ever created. Designed to
                  fit your life, made to move and grow.
                </p>
              </div>
              <a href="#explore" className="white-button button">
                <div>Explore Our Products</div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
